# Generated by Django 5.2 on 2025-04-18 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text="Standard language code (e.g., 'en', 'en-us', 'fr')", max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(help_text="Full name of the language (e.g., 'English', 'French')", max_length=100, verbose_name='Language Name')),
                ('is_active', models.BooleanField(default=True, help_text='Is this language currently available for use?', verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default language for the site?', verbose_name='Is Default')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lithographer CMS', help_text='The public name of the website.', max_length=255, verbose_name='Site Name')),
                ('timezone', models.CharField(default='UTC', help_text="Default timezone for the application (e.g., 'UTC', 'America/New_York').", max_length=100, verbose_name='Timezone')),
                ('default_language', models.OneToOneField(blank=True, help_text='The default language for the site content and interface.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.language', verbose_name='Default Language')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
