# Generated by Django 5.2 on 2025-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='default_content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', help_text='The default status assigned to newly created content instances.', max_length=20, verbose_name='Default Content Status'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='external_integrations',
            field=models.JSONField(blank=True, default=dict, help_text="Store API keys and settings for external services (e.g., {'google_analytics_id': 'UA-XXXXX-Y'}). Use with caution.", verbose_name='External Integrations Config'),
        ),
    ]
