# Generated by Django 5.2 on 2025-04-18 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Hero Banner').", max_length=100, unique=True, verbose_name='Component Name')),
                ('api_id', models.SlugField(help_text="Unique identifier used in APIs and code (e.g., 'hero_banner'). Automatically generated.", max_length=100, unique=True, verbose_name='API ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=255, verbose_name='Icon Class/URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Definition',
                'verbose_name_plural': 'Component Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name for the field (e.g., 'Headline').", max_length=100, verbose_name='Field Name')),
                ('api_id', models.SlugField(help_text="Unique identifier for the field within the Component Definition (e.g., 'headline'). Automatically generated.", max_length=100, verbose_name='API ID')),
                ('field_type', models.CharField(choices=[('text', 'Text (Single Line)'), ('rich_text', 'Rich Text (Multi Line)'), ('number', 'Number (Integer/Float)'), ('date', 'Date/DateTime'), ('boolean', 'Boolean (True/False)'), ('email', 'Email Address'), ('url', 'URL'), ('media', 'Media (Link to Media Library)'), ('relationship', 'Relationship (Link to other Content Instance)'), ('select', 'Select (Dropdown/Radio)'), ('structured_list', 'Structured List (Repeater)'), ('json', 'JSON')], help_text='Determines the kind of data stored and the input widget used.', max_length=50, verbose_name='Field Type')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which fields appear in the component configuration form.', verbose_name='Order')),
                ('config', models.JSONField(blank=True, default=dict, help_text="Field-specific settings (JSON format). Keys include: 'required' (bool), 'default_value', 'help_text' (str), 'select_options' (list for 'select' type), 'allowed_content_types' (list of api_ids for 'relationship' type), 'allowed_media_types' (list for 'media' type).", verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='components.componentdefinition', verbose_name='Component Definition')),
            ],
            options={
                'verbose_name': 'Component Field Definition',
                'verbose_name_plural': 'Component Field Definitions',
                'ordering': ['component_definition', 'order', 'name'],
                'unique_together': {('component_definition', 'api_id')},
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order of this component on the page.', verbose_name='Order')),
                ('data', models.JSONField(blank=True, default=dict, help_text="Stores the configured values for the component's fields, keyed by field API ID.", verbose_name='Component Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='components.componentdefinition', verbose_name='Component Definition')),
                ('page', models.ForeignKey(help_text='The page this component instance belongs to.', limit_choices_to={'content_type__api_id__in': ['page', 'landingpage']}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='content.contentinstance', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Component',
                'verbose_name_plural': 'Page Components',
                'ordering': ['page', 'order'],
                'indexes': [models.Index(fields=['page', 'order'], name='components__page_id_a5bea4_idx')],
            },
        ),
    ]
