# Generated by Django 5.2 on 2025-04-18 06:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(help_text='The URL where the webhook payload should be sent.', max_length=500, verbose_name='Target URL')),
                ('subscribed_events', models.JSONField(blank=True, default=list, help_text="List of event types this webhook listens for (e.g., ['content.published', 'user.created']). Use '*' for all events.", verbose_name='Subscribed Events')),
                ('secret', models.CharField(help_text="A secret key used to sign the webhook payload for verification on the receiver's end.", max_length=255, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook endpoint is currently active and should receive events.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="The specific event that triggered this webhook (e.g., 'content.published').", max_length=100, verbose_name='Event Type')),
                ('payload', models.JSONField(help_text='The JSON data sent in the webhook request.', verbose_name='Payload')),
                ('request_headers', models.JSONField(blank=True, help_text='Headers sent with the webhook request.', null=True, verbose_name='Request Headers')),
                ('response_status_code', models.PositiveIntegerField(blank=True, help_text='HTTP status code received from the target URL.', null=True, verbose_name='Response Status Code')),
                ('response_headers', models.JSONField(blank=True, help_text='Headers received in the webhook response.', null=True, verbose_name='Response Headers')),
                ('response_body', models.TextField(blank=True, help_text='Response body received from the target URL (may be truncated).', verbose_name='Response Body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Delivery Status')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the delivery attempt was made.', verbose_name='Timestamp')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='webhooks.webhookendpoint', verbose_name='Webhook Endpoint')),
            ],
            options={
                'verbose_name': 'Webhook Event Log',
                'verbose_name_plural': 'Webhook Event Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
