# Generated by Django 5.2 on 2025-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='title',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='translated_alt_text',
            field=models.JSONField(blank=True, default=dict, help_text="Alt text in different languages (JSON: {'lang_code': 'Alt Text'}). Important for accessibility.", verbose_name='Translated Alt Text'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='translated_caption',
            field=models.JSONField(blank=True, default=dict, help_text="Caption in different languages (JSON: {'lang_code': 'Caption'}).", verbose_name='Translated Caption'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='translated_title',
            field=models.JSONField(blank=True, default=dict, help_text="Title in different languages (JSON: {'lang_code': 'Title'}). Falls back to filename if empty.", verbose_name='Translated Title'),
        ),
    ]
