# Generated by Django 5.2 on 2025-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='frontenduser',
            name='display_name',
            field=models.CharField(help_text='Publicly visible name (e.g., for comments). Defaults to username if blank.', max_length=150, verbose_name='Display Name'),
        ),
    ]
